---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  selector:
    matchLabels:
      app: a
  replicas: 2
  template:
    metadata:
      labels:
        app: a
    spec:
      containers:
        - name: hello-world-pod
          image: kishlay6/mavenfile:latest
          ports:
            - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: a
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: NodePort
